Page({
  data: {
    contacts: [
      { letter: 'A', name: '安安', title: '运营 · 北京' },
      { letter: 'A', name: '阿强', title: '研发 · 上海' },
      { letter: 'A', name: '艾米', title: '设计 · 杭州' },
      { letter: 'A', name: '艾伦', title: '产品 · 深圳' },
      { letter: 'B', name: '波波', title: '客服 · 成都' },
      { letter: 'B', name: '白洁', title: '市场 · 广州' },
      { letter: 'B', name: '包磊', title: '测试 · 南京' },
      { letter: 'C', name: '陈晨', title: '前端 · 杭州' },
      { letter: 'C', name: '崔崔', title: '后端 · 北京' },
      { letter: 'C', name: '曹雪', title: '数据 · 上海' },
      { letter: 'C', name: '常伟', title: '运维 · 西安' },
      { letter: 'D', name: '东东', title: '销售 · 武汉' },
      { letter: 'D', name: '丁丁', title: '财务 · 天津' },
      { letter: 'D', name: '邓凯', title: '法务 · 重庆' },
      { letter: 'F', name: '方方', title: '运营 · 苏州' },
      { letter: 'F', name: '冯雪', title: '设计 · 厦门' },
      { letter: 'G', name: '高圆', title: '产品 · 青岛' },
      { letter: 'G', name: '郭涛', title: '研发 · 合肥' },
      { letter: 'H', name: '何静', title: '人事 · 郑州' },
      { letter: 'H', name: '黄磊', title: '前端 · 长沙' },
      { letter: 'H', name: '韩梅', title: '客服 · 济南' },
      { letter: 'J', name: '姜瑜', title: '市场 · 大连' },
      { letter: 'J', name: '蒋峰', title: '测试 · 宁波' },
      { letter: 'K', name: '孔亮', title: '后端 · 福州' },
      { letter: 'L', name: '李雷', title: '研发 · 北京' },
      { letter: 'L', name: '林林', title: '产品 · 上海' },
      { letter: 'L', name: '刘洋', title: '运营 · 杭州' },
      { letter: 'L', name: '梁静', title: '设计 · 深圳' },
      { letter: 'L', name: '罗斌', title: '数据 · 成都' },
      { letter: 'M', name: '马超', title: '销售 · 广州' },
      { letter: 'M', name: '孟琪', title: '财务 · 南京' },
      { letter: 'N', name: '倪娜', title: '法务 · 武汉' },
      { letter: 'P', name: '潘婷', title: '人事 · 天津' },
      { letter: 'P', name: '彭宇', title: '运维 · 重庆' },
      { letter: 'Q', name: '秦川', title: '前端 · 西安' },
      { letter: 'Q', name: '齐悦', title: '市场 · 苏州' },
      { letter: 'R', name: '任飞', title: '测试 · 厦门' },
      { letter: 'S', name: '孙悦', title: '产品 · 青岛' },
      { letter: 'S', name: '宋佳', title: '研发 · 合肥' },
      { letter: 'S', name: '沈浩', title: '后端 · 郑州' },
      { letter: 'T', name: '唐雪', title: '设计 · 长沙' },
      { letter: 'T', name: '田野', title: '运营 · 济南' },
      { letter: 'W', name: '王芳', title: '客服 · 大连' },
      { letter: 'W', name: '吴昊', title: '销售 · 宁波' },
      { letter: 'W', name: '魏薇', title: '财务 · 福州' },
      { letter: 'W', name: '汪洋', title: '数据 · 北京' },
      { letter: 'X', name: '徐静', title: '人事 · 上海' },
      { letter: 'X', name: '谢磊', title: '法务 · 杭州' },
      { letter: 'Y', name: '杨帆', title: '前端 · 深圳' },
      { letter: 'Y', name: '叶青', title: '市场 · 成都' },
      { letter: 'Y', name: '于娜', title: '产品 · 广州' },
      { letter: 'Z', name: '张三', title: '研发 · 南京' },
      { letter: 'Z', name: '赵云', title: '运维 · 武汉' },
      { letter: 'Z', name: '周杰', title: '测试 · 天津' },
      { letter: 'Z', name: '郑爽', title: '设计 · 重庆' },
      { letter: 'Z', name: '朱琳', title: '运营 · 西安' }
    ]
  }
});
